### ISSUE TITLE
LOOP: PUSH where PUSHNEW was likely intended

### ISSUE THREAD

**Issue by phoe** [s-expressionists/Khazern#1]
https://github.com/s-expressionists/Khazern/blob/4c8969f51d7313ef1b6c2d09be58301098b3310d/code/for-as-clause.lisp#L60-L61

`add-for-as-subclause-parser` is used with symbols - I assume that `pushnew` is meant instead of `push` in there in order to avoid duplication of parsers and a minor memory leak.

(Moved from https://github.com/robert-strandh/SICL/issues/225)

**Comment by yitzchak** [comment]
Thanks! Fixed by 52c5926
